sonar.projectKey=Sairam-Appsec_crAPI
sonar.organization=sairam-appsec
sonar.host.url=https://sonarcloud.io


sonar.sources=.
sonar.sourceEncoding=UTF-8


sonar.exclusions=**/node_modules/**,**/test/**,**/temp/**